// <auto-generated />
using System;
using LinkedInPortfolio.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkedInPortfolio.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512093351_AddLinkedInOAuth")]
    partial class AddLinkedInOAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CredentialUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileSnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSnapshotId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EndYear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSnapshotId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProfileSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSnapshotId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.ProfileSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProfileSnapshots");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSnapshotId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndorsementCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProfileSnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSnapshotId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkedInId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LinkedInId")
                        .IsUnique()
                        .HasFilter("LinkedInId IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Certification", b =>
                {
                    b.HasOne("LinkedInPortfolio.API.Models.ProfileSnapshot", null)
                        .WithMany("Certifications")
                        .HasForeignKey("ProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Education", b =>
                {
                    b.HasOne("LinkedInPortfolio.API.Models.ProfileSnapshot", null)
                        .WithMany("Educations")
                        .HasForeignKey("ProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Experience", b =>
                {
                    b.HasOne("LinkedInPortfolio.API.Models.ProfileSnapshot", null)
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.ProfileSnapshot", b =>
                {
                    b.HasOne("LinkedInPortfolio.API.Models.User", "User")
                        .WithMany("ProfileSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Project", b =>
                {
                    b.HasOne("LinkedInPortfolio.API.Models.ProfileSnapshot", null)
                        .WithMany("Projects")
                        .HasForeignKey("ProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.Skill", b =>
                {
                    b.HasOne("LinkedInPortfolio.API.Models.ProfileSnapshot", null)
                        .WithMany("Skills")
                        .HasForeignKey("ProfileSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.ProfileSnapshot", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Projects");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LinkedInPortfolio.API.Models.User", b =>
                {
                    b.Navigation("ProfileSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
